### ISSUE TITLE
Windows Atom users ?

### ISSUE THREAD

**Issue by thebluesheep** [lexcast/linter-twig#1]
How to get the linter working on Atom for Windows?
I have installed PHP for linter-php package for Atom in C:\PHP\ ...

**Comment by lexcast** [comment]
umm linter-php? This is the linter-twig for twig templates.
You need to install first [asm89/twig-lint](https://github.com/asm89/twig-lint) to use this package.

**Comment by thebluesheep** [comment]
Yes ... but how to install asm89/twig-lint on a Windows machine ..?
I tried to download the twig-lint.phar file from GIT ... but I am unable to get it to work with the Atom package.

**Comment by lexcast** [comment]
try to execute the phar from your terminal. And put that path in the settings of this package.

**Comment by thebluesheep** [comment]
This command line, will execute linter in windows command prompt ...
c:\php\php.exe c:\php\twig-lint.phar
But the linter-twig package still shows error ...

Error: 
    at parameters.exit (C:\Users....atom\packages\linter-twig\node_modules\atom-linter\lib\helpers.js:58:20)
    at triggerExitCallback (C:\Users...\AppData\Local\atom\app-1.5.3\resources\app.asar\src\buffered-process.js:213:47)
    at C:\Users...\AppData\Local\atom\app-1.5.3\resources\app.asar\src\buffered-process.js:227:18
    at Socket.<anonymous> (C:\Users...\AppData\Local\atom\app-1.5.3\resources\app.asar\src\buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)

**Comment by lexcast** [comment]
I found the problem.
To execute the command I call the exec method of the atom-linter helper, and this method only accepts one string command (I mean without spaces), everything else should be pass as a parameter in an array. That's why it crashes.
I know this is not a solution, but there is a reason for not installing the twig-lint with composer?

**Comment by jmauzyk** [comment]
I'm trying to get linter-twig up and running on my Windows PC and having trouble as well. I have installed twig-lint and am able to locate it, but no matter how I enter the path into linter-twig settings, it seems to throw an error. It lists the path and says it "is not recognized as an internal or external command, operable program or batch file." How can I get this to work?

**Comment by thomasfrobieter** [comment]
Problems on Windows 10 here also. Path is set correctly, if i type "twig-lint --version" it prints out the version (same with "php --version").

No errors in atom, but no function also. Errors are not highlighted :/

Any ideas?

Update: If i change the "twig-lint Path" setting to something false, i got an error, so twig-lint is correctly recognized.

Furher information:
- PHP Version 7.1.2
- Twig lint Version: 1.0.1

**Update 2:** Okay, i think i figured it out. It's about network drives / shares. 

The files are located on a shared folder (NAS) which is initalized as network drive "T:".
If i try "twig-lint lint foo.html.twig" on T:\ i got "File or directory "foo.html.twig" is not readable". 
If i copy the same file on a local drive, it works - resulting message "OK in foo.html.twig".
