### ISSUE TITLE
Runtime Exception on any twig file

### ISSUE THREAD

**Issue by rbaprado** [lexcast/linter-twig#2]
When I simply open any twig file:

```
Error:

[Symfony\Component\Console\Exception\RuntimeException]
The "--only-print-errors" option does not exist.

lint [--format [FORMAT]] [--] []
Error: 

  [Symfony\Component\Console\Exception\RuntimeException]  
  The "--only-print-errors" option does not exist.        

lint [--format [FORMAT]] [--] [<filename>]
    at parameters.exit (/home/buzz/.atom/packages/linter-twig/node_modules/atom-linter/lib/helpers.js:58:20)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
    at ChildProcess.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

**Comment by lexcast** [comment]
Which version of [asm89/twig-lint](https://github.com/asm89/twig-lint) are you using? 
You need to install the dev master branch.

**Comment by rbaprado** [comment]
I was on @stable, changing to @dev solved it. Thanks.
