### ISSUE TITLE
Failed to activate the linter-twig package

### ISSUE THREAD

**Issue by brownsf** [lexcast/linter-twig#4]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [linter-twig](https://github.com/lexcast/linter-twig) package, v0.1.1
### Stack Trace

Failed to activate the linter-twig package

```
At Cannot find module 'sb-callsite'

Error: Cannot find module 'sb-callsite'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.install (/Users/macuser/.atom/packages/linter-twig/node_modules/atom-package-deps/lib/main.js:14:22)
    at Object.module.exports.activate (/Users/macuser/.atom/packages/linter-twig/lib/main.coffee:11:34)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:389:60
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:229:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
### Commands

```
     -4:58.5.0 core:save (atom-text-editor.editor.is-focused)
  6x -4:41.1.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:24.1.0 core:copy (atom-text-editor.editor.is-focused)
  2x -4:16.4.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -4:15.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -4:14.5.0 core:paste (atom-text-editor.editor.is-focused)
     -3:56 core:save (atom-text-editor.editor.is-focused)
     -3:12.1.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -3:10.7.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:34 core:backspace (atom-text-editor.editor.is-focused)
  2x -2:29.5.0 core:move-down (atom-text-editor.editor.is-focused)
     -2:28.9.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -2:28.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:14.3.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:09.7.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:37.4.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
```
### Config

``` json
{
  "core": {
    "openEmptyEditorOnStart": false
  }
}
```
### Installed Packages

``` coffee
# User
aligner-php, v1.0.0
auto-detect-indentation, v1.0.0
autoclose-html, v0.23.0
autocomplete-php, v0.3.7
emmet, v2.4.3
file-icons, v1.7.8
highlight-line, v0.11.1
language-twig, v1.6.3
linter, v1.11.4
linter-csslint, v1.3.2
linter-htmlhint, v1.1.0
linter-jshint, v2.0.3
linter-php, v1.2.0
linter-twig, v0.1.1
react, v0.15.0
react-es6-snippets, v0.3.0
redux-snippets, v0.2.2

# Dev
No dev packages
```

**Comment by lexcast** [comment]
Now we are using a newest version of atom-package-deps.
@brownsf can you try install again?
