### ISSUE TITLE
The "--only-print-errors" option does not exist.

### ISSUE THREAD

**Issue by deelite** [lexcast/linter-twig#5]
When I try do edit twig files I get this error:

Error:

[RuntimeException]
The "--only-print-errors" option does not exist.

lint [--format [FORMAT]] [--] []
Error: 

  [RuntimeException]  
  The "--only-print-errors" option does not exist.  

lint [--format [FORMAT]] [--] [<filename>]
    at parameters.exit (/Users/jan/.atom/packages/linter-twig/node_modules/atom-linter/lib/helpers.js:58:20)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:237:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

I use Atom 1.8 with the latest release of linter-twig.

At the moment I can't use Atom for twig files with linter.

**Comment by lexcast** [comment]
which version of twig-lint are you using?

**Comment by deelite** [comment]
linter-twig 0.1.1

**Comment by lexcast** [comment]
use the dev-master version

```
composer global require "asm89/twig-lint" "@dev"
```

**Comment by deelite** [comment]
that's cool. it works. thank you!
